In [2]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\Mr. COMPUTER\Desktop\DEEP LEARNING NLP\myenv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\Mr. COMPUTER\Desktop\DEEP LEARNING NLP\myenv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\Mr. COMPUTER\Desktop\DEEP LEARNING NLP\myenv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/

In [3]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# One Hot Representation
 
#one_hot(words,voc_size)for words in sent 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8453, 2721, 2202, 8072],
 [8453, 2721, 2202, 2652],
 [8453, 5756, 2202, 4915],
 [2366, 9831, 9539, 8091, 7243],
 [2366, 9831, 9539, 8091, 6383],
 [4124, 8453, 6545, 2202, 177],
 [2590, 57, 476, 8091]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8453 2721 2202 8072]
 [   0    0    0    0 8453 2721 2202 2652]
 [   0    0    0    0 8453 5756 2202 4915]
 [   0    0    0 2366 9831 9539 8091 7243]
 [   0    0    0 2366 9831 9539 8091 6383]
 [   0    0    0 4124 8453 6545 2202  177]
 [   0    0    0    0 2590   57  476 8091]]


In [ ]:
## feature representation
dim=10 #dimensions

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([[[ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.03394606,  0.00420564,  0.00755916,  0.04898865,
         -0.02722701,  0.03248299, -0.02602658, -0.04885805,
          0.04144073,  0.02489752],
        [-0.01565169,  0.04301392,  0.00309689, -0.00670338,
          0.02544909,  0.046467  , -0.0176456 , -0.03729975,
         -0.01159537,  0.00287837],
        [-0.01550878, -0.01588885, -0.00611664, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8453, 2721, 2202, 8072], dtype=int32)

In [18]:
model.predict(embedded_docs[0][None, :])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.0382571 ,  0.03033156,  0.0398804 ,  0.0486894 ,
          0.02701967, -0.02875528, -0.00608286,  0.02633617,
          0.02489612,  0.00480761],
        [ 0.03394606,  0.00420564,  0.00755916,  0.04898865,
         -0.02722701,  0.03248299, -0.02602658, -0.04885805,
          0.04144073,  0.02489752],
        [-0.01565169,  0.04301392,  0.00309689, -0.00670338,
          0.02544909,  0.046467  , -0.0176456 , -0.03729975,
         -0.01159537,  0.00287837],
        [-0.01550878, -0.01588885, -0.00611664, -0.0